### ISSUE TITLE
waxy grey caederine 

### ISSUE THREAD

**Issue by sandersch** [elanthia-online/scripts#129]
## 🤔 Expected Behavior

[waxy grey caederine](https://gswiki.play.net/Waxy_grey_caederine) should be in the GameObj data.

## 😯 Current Behavior

Missing entirely.

## 💁 Possible Solution

Probably belongs in the same categories as [ambergris](https://github.com/elanthia-online/scripts/issues/106).

## 🔦 Context

Came up in Discord discussion today. Asked @HebrewToYou to save some next time he sees it in the Rift so we can test it out.

## 💻 Examples

"waxy grey caederine" is only description afaik.

**Comment by sandersch** [comment]
[8:37 PM] HebrewToYou: officially confirmed: can only be sold to pawnshop or furrier. Worth 3x as much when sold to the furrier.

**Comment by sandersch** [comment]
Looks like this should be:

**type:** skin
**sellable:** furrier

just like ambergris

**Comment by ondreian** [comment]
I have reservations about how we are handling ambergris and caederine type items.

They should not have type `skin`, but should be sellable `furrier`, there is no way to cross reference what was something generated via the `SKIN` verb otherwise.

Loot scripts not relying on both `sellable` and `type` info are buggy, imo.

For reference this is an issue i am currently experiencing when running my selling script:
```
;lucre sell --furrier --skins=false
```
will not sell ambergris, but it should

**Comment by sandersch** [comment]
I think that's a reasonable point. I would be fine with only adding caederine to the furrier sellable list and considering the removal of ambergris and similar items from the skin type.

**Comment by sandersch** [comment]
In #265 I am updating these to be sellable at the furrier, but have a type of `reagent`. They are a primary ingredient in many of the dye formulas and can be stored in jars like other reagents.
