### ISSUE TITLE
jinx: add data cli command

### ISSUE THREAD

**Issue by ondreian** [elanthia-online/scripts#370]
```
;jinx data update <definition>
```
examples:
```
;jinx data update mapdb
;jinx data update spells
;jinx data update gameobj
```

**Comment by sandersch** [comment]
Thinking about tackling this since the pain of being unable to update spell-list-xml is rather acute.

The client script changes to [jinx](https://github.com/elanthia-online/scripts/blob/master/scripts/jinx.lic) seem pretty straightforward to me. Your examples above only include the `update` cmd but `list` and `install` are probably necessary too. `update` and `info` seem less important but would be nice to have and probably wouldn't be difficult to adapt from the script versions.

@ondreian Do you think we need to make any changes to [jinxp](https://github.com/elanthia-online/jinxp) to support these commands? My thought was that data files would be published as a separate repo and the manifest is ambivalent about asset type, but you have a better understanding so would appreciate your input.

**Comment by ondreian** [comment]
`jinxp` definitely needs some updates, I was thinking the `available` assets should have a `type` attribute going forward, `.{lic,rb}` would be script, anything else is `data` as a way to delineate which systems work with which.

**Comment by ondreian** [comment]
The `type` attribute for jinxp would probably go here:
https://www.github.com/elanthia-online/jinxp/tree/main/src%2Fasset.cr

I'm not sure how familiar with crystal you are, but it's fairly close to Ruby, i didn't have time to figure out how to write a github action to run the `crystal spec` command the other day, so CI is not running there

**Comment by sandersch** [comment]
Crystal is perfectly readable to me and I have played around with it but haven't had a reason to use it for anything non-trivial yet. If something does need to be updated, that would be a good reason for me to learn more so no problem.
