### ISSUE TITLE
[gameobj] herbs, common gems, EG gems

### ISSUE THREAD

**Issue by gs4onurb** [elanthia-online/scripts#817]
### Brief Description

Found some herbs and gemshop sellables/valuables not in the database.

update: all rooms tagged with herbs, ebon gate gems added.

sellable name="gemshop"
piece of petrified haon
piece of petrified maoral
piece of petrified modwir
piece of petrified thanot **(missing)**

type name="valuable"
piece of petrified haon
piece of petrified maoral **(missing)**
piece of petrified modwir
piece of petrified thanot **(missing)**

**Comment by mrhoribu** [comment]
Looks like the EG gems were resolved already with a PR that Alastir submitted via #833 .

The herbs you mention aren't necessarily herbs in the sense that gameobj-type looks at them. herbs tagged as such in GameObj are actual medicinal herbs that are used for healing. Several scripts use this designation specifically for that reason. The items you are asking for are mostly just foragables. We should likely add a new category for these as there is a huge range of forageables now that was released due to all the new cooking/forage updates. Unless you're more specifically asking for them to be included in the mapdb for easier finding. If so, that's not managed by EO and anyone can really just go add forage tags to rooms via a few scripts (can't recall them off top of my head) that are on the `;repo` already.

As for the gemshop/valuable, I'll see about getting those added as those look to be good to go from what I can tell.

**Comment by gs4onurb** [comment]
The herbs listed were all given for a bounty tasks and zzentar's herb finding script, which is pretty popular script from what I understand, cannot find those bounty herbs.

**Comment by mrhoribu** [comment]
> The herbs listed were all given for bounty tasks and zzentar's herb finding script, which is pretty popular script from what I understand, cannot find those bounty herbs.

Yep, that would be a mapdb issue then, not a gameobj-data.xml issue. You can fix these yourself by just checking out the mapdb ingame and using the `;tags` script via `;tags --sense` and once done, upload the mapdb.

```
Step1: Checkout mapdb via ;repo checkout-mapdb
Step2: Update various rooms with new herbs via ;tags --sense
Step3: Upload mapdb via ;repo upload-mapdb
Step4: Profit!
```

**Comment by gs4onurb** [comment]
Thank you for the info and instruction, will do tonight.
